import type { Metadata } from "next";

import {GlobalProvider} from "@/context/globalContext";
import Navbar from "@/components/navbar";
import ThemeRegistry from "@/theme/themeRegistry";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
      <GlobalProvider>
       <ThemeRegistry>
           <Navbar/>
           {children}
       </ThemeRegistry>
      </GlobalProvider>
      </body>
    </html>
  );
}
